const { RELEASE_RULES, CHANGELOG_TYPES } = require('./release.rules.cjs');

const DEV_NUM = process.env.DEV_NUM
const DEV_SUFFIX = DEV_NUM ? `.dev${process.env.DEV_NUM}` : '';

module.exports = {
    // You can find out more about the configuration of this file here https://semantic-release.gitbook.io/semantic-release/usage/configuration
    "branches": [
        { "name": 'master' },
        { "name": 'release/*', "prerelease": 'rc' },
        { "name": 'develop', "prerelease": 'alpha' },
    ],
    "tagFormat": '${version}' + DEV_SUFFIX,
    // "tagFormat": 'v${version}',
    // "tagFormat": '${version}',
    // Plugins https://semantic-release.gitbook.io/semantic-release/extending/plugins-list
    "plugins": [
        [
            // Analyzes commits and determines which release version should be released.
            '@semantic-release/commit-analyzer',
            {
                "preset": 'conventionalcommits',
                // Define the commits that will increase the release version
                "releaseRules": RELEASE_RULES,
            },
        ],
        // './.github/workflows/plugins/release-dev-suffix.cjs',
        [
            // Add release notes
            '@semantic-release/release-notes-generator',
            {
                "preset": 'conventionalcommits',
                // Define the commits that will be described in the release notes
                "presetConfig": { "types": CHANGELOG_TYPES },
            },
        ],
        [
            // Writing release notes to a changelog
            '@semantic-release/changelog',
            { 
                "changelogTitle": "# Changelog",
                "changelogFile": 'CHANGELOG.md' 
            },
        ],
        [
            // Bumping version in pyproject.toml and build .whl
            '@semantic-release/exec', 
            {
                "prepareCmd": 'echo "${nextRelease.version}" && poetry version ${nextRelease.version} && poetry build',
            }
        ],
        [
            // Plugin for commits changes
            '@semantic-release/git',
            {
                "assets": ['CHANGELOG.md', 'pyproject.toml'],
                // "assets": ['CHANGELOG.md',],
                "message":
                    'chore(release): ${nextRelease.version} [skip ci]\n\n' +
                    'Automatically generated by semantic-release'
            },
        ],
        [
            // Release to Github with builded files 
            '@semantic-release/github', 
            {
                "assets": [
                    { "path": 'dist/*' }
                ],
            }
        ],
    ],
};