const { RELEASE_RULES, CHANGELOG_TYPES } = require('./release.rules.cjs');

function toPep440(version) {
    const [base, ...rest] = version.split('-');

    if (rest.length === 0)
        return version;

    const identifier = rest.join('-');
    if (/^[A-Za-z]+\.\d+$/.test(identifier)) 
        return version;

    const num = identifier.split('.').pop();
    const phase = identifier.includes('develop') ? 'alpha' : 'rc';

    return `${base}-${phase}.${num}`;
}

module.exports = {
    // You can find out more about the configuration of this file here https://semantic-release.gitbook.io/semantic-release/usage/configuration
    "branches": [
        { "name": 'master' }, 
        { "name": 'release/*', "prerelease": 'rc' },
        { "name": 'develop', "prerelease": 'alpha' },
        { "name": '*/master', "range": '${name.match(/^(\\d+)\\.x/)[1]}.x' },
        { "name": '{*/develop,*/release/*}', "prerelease": '${name.replace(/\\//g, "-")}' }
    ],
    "tagFormat": '${version}',
    // Plugins https://semantic-release.gitbook.io/semantic-release/extending/plugins-list
    "plugins": [
        [
            // Analyzes commits and determines which release version should be released.
            '@semantic-release/commit-analyzer',
            {
                "preset": 'conventionalcommits',
                // Define the commits that will increase the release version
                "releaseRules": RELEASE_RULES,
            },
        ],
        // './.github/workflows/plugins/release-dev-suffix.cjs',
        [
            // Add release notes
            '@semantic-release/release-notes-generator',
            {
                "preset": 'conventionalcommits',
                // Define the commits that will be described in the release notes
                "presetConfig": { "types": CHANGELOG_TYPES },
            },
        ],
        [
            // Writing release notes to a changelog
            '@semantic-release/changelog',
            { 
                "changelogTitle": "# Changelog",
                "changelogFile": 'CHANGELOG.md' 
            },
        ],
        {
            prepare: async (pluginConfig, context) => {
                process.env.PEP440_VERSION = toPep440(context.nextRelease.version);
            },
        },
        [
            // Bumping version in pyproject.toml and build .whl
            '@semantic-release/exec', 
            {
                "prepareCmd": 'poetry version "$PEP440_VERSION" && poetry build',
                // The entry below helps determine whether a new release was published 
                // or not during the execution of the release workflow.
                "successCmd": 'echo "released=true" >> $GITHUB_OUTPUT'
            }
        ],
        [
            // Plugin for commits changes
            '@semantic-release/git',
            {
                "assets": ['CHANGELOG.md', 'pyproject.toml'],
                "message":
                    'chore(release): ${nextRelease.version}\n\n' +
                    'Automatically generated by semantic-release'
            },
        ],
        [
            // Release to Github with builded files 
            '@semantic-release/github', 
            {
                "assets": [
                    { "path": 'dist/*' }
                ],
            }
        ],
    ],
};