name: Create and publish release 

on:
  push:
    branches:
      # Main branches group
      - 'master'
      - 'release/*'
      - 'hotfix/*'
      - develop
      # Maintenace branches group
      - '*/master'
      - '*/release/*'
      - '*/hotfix/*'
      - '*/develop'
  # If this trigger is removed, the automatic publication of release 
  # N.N.N-rc.1 will not happen when the release branch is created.
  pull_request:
    branches:
      - 'master'
      - '*/master'
    types: [opened, reopened]
  # If this trigger is removed, then in the event that a release 
  # publication is terminated for unknown reasons (for example, 
  # an attempt to publish an existing tag), it will be difficult 
  # to restart the workflow without publishing a new commit
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # The job is needed to check whether a commit is a service commit, 
  # in order to restrict the execution of workflows on service commits
  detect_semantic_release_service_commit:
    name: Detect semantic-release service commit
    runs-on: ubuntu-24.04
    outputs:
      skip: ${{ steps.check.outputs.IS_SERVICE_COMMIT }}
    env:
      COMMIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

    steps:
      - uses: actions/checkout@v7
        with:
          # 1: If checkout is performed by branch name, there is a chance that 
          # a commit pushed between the workflow trigger and the `detect` job 
          # will be subject to this check
          # 
          # 2: When triggered by the `pull_request` event, `github.sha` points 
          # to a service merge commit, so we must use `github.event.pull_request.head.sha`
          ref: ${{ env.COMMIT_SHA }}

      - id: check
        name: Detect semantic-release service commit
        run: |
          AUTHOR_NAME="$(git log -1 --pretty='%an')"
          COMMIT_MESSAGE="$(git log -1 --pretty='%s')"

          if [[ "$AUTHOR_NAME" == "semantic-release-bot" \
                && "$COMMIT_MESSAGE" =~ ^chore\(release\):.* ]]; then
            echo "The commit with hash '${{ env.COMMIT_SHA }}' is a service commit; workflow skip"
            echo "IS_SERVICE_COMMIT=true" >> "$GITHUB_OUTPUT"
          else
            echo "The commit with hash '${{ env.COMMIT_SHA }}' is not a service commit; continuing the workflow"
            echo "IS_SERVICE_COMMIT=false" >> "$GITHUB_OUTPUT"
          fi

  publish_release:
    name: Create and publish release 
    runs-on: ubuntu-24.04
    needs:
      - detect_semantic_release_service_commit
    if: needs.detect_semantic_release_service_commit.outputs.IS_SERVICE_COMMIT != 'true'
    concurrency:
      group: ${{ github.workflow }}-release-${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
      cancel-in-progress: false

    steps:
      - name: Checkout repository on release branch
        uses: actions/checkout@v7
        with:
          # If a workflow is triggered by a `pull_request` event, `actions/checkout` 
          # without an explicit `ref` will checkout to the `refs/pull/<PR-id>/merge` 
          # branch, which will break the semantic release logic
          # https://github.com/actions/checkout#push-a-commit-to-a-pr-using-the-built-in-token
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.TEMP_SEMANTIC_RELEASE_GH_TOKEN }}

      - name: Force release branch to be at workflow sha
        run: |
          # When a PR is created, GitHub generates a "synthetic" commit 
          # that simulates a merge, which is why `github.sha` refers to 
          # it instead of the actual latest commit in the branch.
          git reset --hard ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

      - name: Verify upstream has NOT changed
        shell: bash
        run: |
          set +o pipefail

          UPSTREAM_BRANCH_NAME="$(git status -sb | head -n 1 | awk -F '\\.\\.\\.' '{print $2}' | cut -d ' ' -f1)"
          printf '%s\n' "Upstream branch name: $UPSTREAM_BRANCH_NAME"

          set -o pipefail

          if [ -z "$UPSTREAM_BRANCH_NAME" ]; then
              printf >&2 '%s\n' "::error::Unable to determine upstream branch name!"
              exit 1
          fi

          git fetch "${UPSTREAM_BRANCH_NAME%%/*}"

          if ! UPSTREAM_SHA="$(git rev-parse "$UPSTREAM_BRANCH_NAME")"; then
              printf >&2 '%s\n' "::error::Unable to determine upstream branch sha!"
              exit 1
          fi

          HEAD_SHA="$(git rev-parse HEAD)"

          if [ "$HEAD_SHA" != "$UPSTREAM_SHA" ]; then
              printf >&2 '%s\n' "[HEAD SHA] $HEAD_SHA != $UPSTREAM_SHA [UPSTREAM SHA]"
              printf >&2 '%s\n' "::error::Upstream has changed, aborting release..."
              exit 1
          fi

          printf '%s\n' "Verified upstream branch has not changed, continuing with release..."

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.18.0
      
      # [!] Start of the stack-dependent section

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: '2.4.1'
          virtualenvs-create: true
          virtualenvs-in-project: true

      # [!] End of the stack-dependent section

      - name: Install semantic-release and plugins
        run: |
          npm install \
            semantic-release@25.0.3 \
            @semantic-release/exec@7.1.0 \
            @semantic-release/commit-analyzer@13.0.1 \
            @semantic-release/release-notes-generator@14.1.1 \
            @semantic-release/changelog@6.0.3 \
            @semantic-release/git@10.0.1 \
            @semantic-release/github@12.0.8 \
            conventional-changelog-conventionalcommits@9.3.1
      
      - name: Semantic Version Release
        id: semantic_version_release
        env:
          # this token should have at lease these permissions:
          #   contents: write # to be able to publish a GitHub release
          #   issues: write # to be able to comment on released issues
          #   pull-requests: write # to be able to comment on released pull requests
          GH_TOKEN: ${{ secrets.TEMP_SEMANTIC_RELEASE_GH_TOKEN   }}
        run: |
          unset GITHUB_ACTIONS
          npx semantic-release